assert(SMODS.load_file("src/defs/atlases.lua"))()
assert(SMODS.load_file("src/defs/stickers.lua"))()
assert(SMODS.load_file("src/defs/stakes.lua"))()
assert(SMODS.load_file("src/defs/jokers.lua"))()
assert(SMODS.load_file("src/defs/product.lua"))()